---
name: Scan Image

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  scan-image:
    name: Scan Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Build Image
        id: build_image
        uses: docker/build-push-action@94f8f8c2eec4bc3f1d78c1755580779804cb87b2 # v6.0.1
        with:
          push: false
          load: true
          tags: visual-studio-code

      - name: Scan Image
        id: scan_image
        uses: aquasecurity/trivy-action@595be6a0f6560a0a8fc419ddf630567fc623531d # v0.22.0
        with:
          image-ref: visual-studio-code
          exit-code: 1
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL
          limit-severities-for-sarif: true

      - name: Scan Image (On SARIF Scan Failure)
        if: failure() && steps.scan_image.outcome == 'failure'
        id: scan_image_on_failure
        uses: aquasecurity/trivy-action@595be6a0f6560a0a8fc419ddf630567fc623531d # v0.22.0
        with:
          image-ref: visual-studio-code
          exit-code: 1
          format: table
          severity: CRITICAL

      - name: Upload SARIF
        if: always()
        id: upload_sarif
        uses: github/codeql-action/upload-sarif@23acc5c183826b7a8a97bce3cecc52db901f8251 # v3.25.10
        with:
          sarif_file: trivy-results.sarif
